### ISSUE TITLE
Dependency issues with Composer

### ISSUE THREAD

**Issue by barry1955** [mvlabs/MvlabsSnappy#8]
Hi,
As part of my project I need to use OAuth2 with Doctrine and MvlabsSnappy. 

In order to get the api modules, I needed to upgrade to zend-framework\framework 3.0 

That is causing a dependency clash with MvlabsSnappy.

Has anyone else seen this issue? How did you get around it?
I thought of cloning the repository and using a local copy.  Is this the best option?

**Comment by barry1955** [comment]
Is this project still alive? 
This dependency thing is holding up future work.  
Should we be looking for different PDF package.

**Comment by drigani** [comment]
Yes, I have planned to release a new version that will upgrade the dependencies to ZF3 in the near future.
If you are interested in contributing, PR are welcomed!

**Comment by drigani** [comment]
@barry1955 done!
